---
apiVersion: skaffold/v2beta29
kind: Config

build:
  tagPolicy:
    gitCommit: { }
  artifacts:
    - image: registry.code.wabo.run/ai/zivid-nova/zivid-nova
      docker:
        buildArgs:
          platform: "linux/amd64"

deploy:
  helm:
    releases:
      - name: zivid-nova
        chartPath: helm/
        createNamespace: true
        namespace: zivid-nova
        skipBuildDependencies: true
        setValueTemplates:
          # see also templated fields https://skaffold.dev/docs/environment/templating/
          tag: "{{.IMAGE_TAG_registry_code_wabo_run_ai_zivid_nova_zivid_nova}}"
          registry: "registry.code.wabo.run/ai/zivid-nova/zivid-nova"
          secretsName: "pull-secret-registry-code-wabo-run"
