# yamllint disable rule:truthy
# yamllint disable rule:document-start
__version__:
  serializer: 1
  data: 5
Settings2D:
  Acquisitions:
    - Acquisition:
        Aperture: 8.72
        Brightness: 0
        ExposureTime: 35000
        Gain: 3
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
      Gamma: 1
  Sampling:
    Color: rgb
    Pixel: all
