apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# adjust depending on your setup
namespace: cell

resources:
  - app.yaml

images:
  - name: wandelbots.azurecr.io/nova-services/zivid-intel
    newTag: 0.0.1
