---
name: Catalog Update

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

env:
  REGISTRY: wandelbots.azurecr.io
  IMAGE_NAME: nova-apps/zivid-nova

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: wandelbotsgmbh/catalog
          token: ${{ secrets.CATALOG_TOKEN }}

      # yamllint disable rule:line-length
      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: yq -i -I4 '.app.containerImage.image = "wandelbots.azurecr.io/nova-services/zivid-intel:1.0.0"' catalog/zivid-intel/manifest.yaml && yq -i -I4 '.version = "1.0.0"' catalog/zivid-intel/manifest.yaml

      - name: Update Catalog
        # if: steps.release.outputs.version != ''
        # yamllint disable rule:line-length
        env:
          GH_TOKEN: ${{ secrets.CATALOG_TOKEN }}
        run: |
          git checkout -b feature/update-zivid-nova-to-1.0.0
          git add catalog/zivid-intel/manifest.yaml
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Update Zivid to 1.0.0"
          git push -u origin feature/update-zivid-nova-to-1.0.0
          gh pr create --fill
