---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

env:
  REGISTRY: wandelbots.azurecr.io
  IMAGE_NAME: nova-apps/zivid-nova

jobs:
  release-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: abatilo/actions-poetry@v2
      - uses: docker/setup-buildx-action@v3

      - name: Bump Version
        uses: go-semantic-release/action@v1
        id: release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Azure Container Registry
        if: steps.release.outputs.version != ''
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PUBLIC_REGISTRY_CI_SCOPE_NOVA_SERVICES_USERNAME }}
          password: ${{ secrets.PUBLIC_REGISTRY_CI_SCOPE_NOVA_SERVICES_TOKEN }}

      - name: Push Docker Image
        if: steps.release.outputs.version != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.release.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Bump Pyproject
        if: steps.release.outputs.version != ''
        run: poetry version ${{ steps.release.outputs.version }}

      - uses: EndBug/add-and-commit@v9
        if: steps.release.outputs.version != ''
        with:
          message: "chore(version): bump"
          default_author: github_actions
          add: pyproject.toml
