---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

env:
  REGISTRY: wandelbots.azurecr.io
  IMAGE_NAME: nova-apps/zivid-intel

jobs:
  release-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: abatilo/actions-poetry@v2
      - uses: docker/setup-buildx-action@v3

      - name: Bump Version
        uses: go-semantic-release/action@v1
        id: release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Azure Container Registry
        if: steps.release.outputs.version != ''
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PUBLIC_REGISTRY_CI_SCOPE_NOVA_SERVICES_USERNAME }}
          password: ${{ secrets.PUBLIC_REGISTRY_CI_SCOPE_NOVA_SERVICES_TOKEN }}

      - name: Push Docker Image
        if: steps.release.outputs.version != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.release.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Bump Pyproject
        if: steps.release.outputs.version != ''
        run: poetry version ${{ steps.release.outputs.version }}

      - name: Commit Pyproject Updates
        uses: EndBug/add-and-commit@v9
        if: steps.release.outputs.version != ''
        with:
          message: "chore(version): bump"
          default_author: github_actions
          add: pyproject.toml

      - name: Checkout Catalog Repo
        uses: actions/checkout@v4
        if: steps.release.outputs.version != ''
        with:
          repository: wandelbotsgmbh/catalog
          token: ${{ secrets.CATALOG_TOKEN }}

      - name: Set Zivid Versions
        if: steps.release.outputs.version != ''
        uses: mikefarah/yq@master
        with:
          # yamllint disable rule:line-length
          cmd: |
            yq -i -I4 '.app.containerImage.image = "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.release.outputs.version }}"' catalog/zivid-intel/manifest.yaml \
            && yq -i -I4 '.version = "${{ steps.release.outputs.version }}"' catalog/zivid-intel/manifest.yaml
          # yamllint enable rule:line-length

      - name: Update Catalog
        if: steps.release.outputs.version != ''
        env:
          GH_TOKEN: ${{ secrets.CATALOG_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b feature/update-zivid-nova-to-${{ steps.release.outputs.version }}
          git add catalog/zivid-intel/manifest.yaml
          git commit -m "Update Zivid to ${{ steps.release.outputs.version }}"
          git push -u origin feature/update-zivid-nova-to-${{ steps.release.outputs.version }}
          gh pr create --fill
          gp pr merge --squash --auto
